apiVersion: apps/v1
kind: Deployment
metadata:
  name: random-data-generation
  labels:
    app: random-data-generation
spec:
  replicas: 3
  selector:
    matchLabels:
      app: random-data-generation
  template:
    metadata:
      labels:
        app: random-data-generation
    spec:
      containers:
      - name: random-data-generation
        image: random_data_generation:v1.0.0
        imagePullPolicy: Never # Use the local image
        ports:
        - containerPort: 5000
        livenessProbe:
          httpGet:
            path: /generate-data
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /generate-data
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10