apiVersion: v1
kind: Service
metadata:
  name: random-data-generation
spec:
  selector:
    app: random-data-generation
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: NodePort